CREATE PROCEDURE uspInsertShiftReport (
    IN Sortkey VARCHAR(50),
    IN Date VARCHAR(50),
    IN Loom VARCHAR(50),
    IN Style VARCHAR(50),
    IN RPM VARCHAR(10),
    IN EfficPercent VARCHAR(50),
    IN RunMinute VARCHAR(50),
    IN StopMinute VARCHAR(50),
    IN ProductPick VARCHAR(255),
    IN WarpCount VARCHAR(50),
    IN WarpMinute VARCHAR(50),
    IN WarpRatePH VARCHAR(50),
    IN WarpRatePDAY VARCHAR(50),
    IN WarpRatePP VARCHAR(50),
    IN Weft_Count VARCHAR(50),
    IN WeftMinute VARCHAR(50),
    IN WeftRatePH VARCHAR(50),
    IN WeftRatePDAY VARCHAR(50),
    IN WeftRatePP VARCHAR(50),
    IN UnselectCount VARCHAR(50),
    IN UnselectMinute VARCHAR(50),
    IN Unselect2Count VARCHAR(50),
    IN UnselectRatePH VARCHAR(50),
    IN UnselectRatePDAY VARCHAR(50),
    IN UnselectRatePP VARCHAR(50),
    IN TotalCount VARCHAR(50),
    IN TotalMinute VARCHAR(50),
    IN Total2Count VARCHAR(50),
    IN TotalRatePH VARCHAR(50),
    IN TotalRatePDAY VARCHAR(50),
    IN TotalRatePP VARCHAR(50)
    )
BEGIN

INSERT INTO tblshiftreport (
    Sortkey,
    Date,
    Loom,
    Style,
    RPM ,
    EfficPercent,
    RunMinute,
    StopMinute,
    ProductPick,
    WarpCount,
    WarpMinute,
    WarpRatePH,
    WarpRatePDAY,
    WarpRatePP,
    Weft_Count,
    WeftMinute,
    WeftRatePH,
    WeftRatePDAY,
    WeftRatePP,
    UnselectCount,
    UnselectMinute,
    Unselect2Count,
    UnselectRatePH,
    UnselectRatePDAY,
    UnselectRatePP,
    TotalCount,
    TotalMinute ,
    Total2Count,
    TotalRatePH,
    TotalRatePDAY,
    TotalRatePP
    )
VALUES (
    Sortkey,
    Date,
    Loom,
    Style,
    RPM ,
    EfficPercent,
    RunMinute,
    StopMinute,
    ProductPick,
    WarpCount,
    WarpMinute,
    WarpRatePH,
    WarpRatePDAY,
    WarpRatePP,
    Weft_Count,
    WeftMinute,
    WeftRatePH,
    WeftRatePDAY,
    WeftRatePP,
    UnselectCount,
    UnselectMinute,
    Unselect2Count,
    UnselectRatePH,
    UnselectRatePDAY,
    UnselectRatePP,
    TotalCount,
    TotalMinute ,
    Total2Count,
    TotalRatePH,
    TotalRatePDAY,
    TotalRatePP
    );

END $$
